/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbbasidRouteImport } from './routes/abbasid'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AlAndalusRouteImport } from './routes/al-andalus'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as BattlesRouteImport } from './routes/battles'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as EmpiresRouteImport } from './routes/empires'
import { Route as FirstWahiRouteImport } from './routes/first-wahi'
import { Route as GoldenAgeRouteImport } from './routes/golden-age'
import { Route as HeroesRouteImport } from './routes/heroes'
import { Route as HijrahRouteImport } from './routes/hijrah'
import { Route as KhulafaRouteImport } from './routes/khulafa'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as OttomanRouteImport } from './routes/ottoman'
import { Route as PalestineRouteImport } from './routes/palestine'
import { Route as PreIslamRouteImport } from './routes/pre-islam'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProphetRouteImport } from './routes/prophet'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ScholarsRouteImport } from './routes/scholars'
import { Route as ScientistsRouteImport } from './routes/scientists'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as UmayyadRouteImport } from './routes/umayyad'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as CountriesIndexRouteImport } from './routes/countries.index'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as EmpiresIndexRouteImport } from './routes/empires.index'
import { Route as EmpiresSlugRouteImport } from './routes/empires.$slug'
import { Route as HeroesIndexRouteImport } from './routes/heroes.index'
import { Route as HeroesSlugRouteImport } from './routes/heroes.$slug'
import { Route as ScientistsIndexRouteImport } from './routes/scientists.index'
import { Route as ScientistsSlugRouteImport } from './routes/scientists.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbbasidRoute = AbbasidRouteImport.update({
  id: '/abbasid',
  path: '/abbasid',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlAndalusRoute = AlAndalusRouteImport.update({
  id: '/al-andalus',
  path: '/al-andalus',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlesRoute = BattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpiresRoute = EmpiresRouteImport.update({
  id: '/empires',
  path: '/empires',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstWahiRoute = FirstWahiRouteImport.update({
  id: '/first-wahi',
  path: '/first-wahi',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldenAgeRoute = GoldenAgeRouteImport.update({
  id: '/golden-age',
  path: '/golden-age',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesRoute = HeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const HijrahRoute = HijrahRouteImport.update({
  id: '/hijrah',
  path: '/hijrah',
  getParentRoute: () => rootRouteImport,
} as any)
const KhulafaRoute = KhulafaRouteImport.update({
  id: '/khulafa',
  path: '/khulafa',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const OttomanRoute = OttomanRouteImport.update({
  id: '/ottoman',
  path: '/ottoman',
  getParentRoute: () => rootRouteImport,
} as any)
const PalestineRoute = PalestineRouteImport.update({
  id: '/palestine',
  path: '/palestine',
  getParentRoute: () => rootRouteImport,
} as any)
const PreIslamRoute = PreIslamRouteImport.update({
  id: '/pre-islam',
  path: '/pre-islam',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProphetRoute = ProphetRouteImport.update({
  id: '/prophet',
  path: '/prophet',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarsRoute = ScholarsRouteImport.update({
  id: '/scholars',
  path: '/scholars',
  getParentRoute: () => rootRouteImport,
} as any)
const ScientistsRoute = ScientistsRouteImport.update({
  id: '/scientists',
  path: '/scientists',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const UmayyadRoute = UmayyadRouteImport.update({
  id: '/umayyad',
  path: '/umayyad',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountriesRoute,
} as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CountriesRoute,
} as any)
const EmpiresIndexRoute = EmpiresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpiresRoute,
} as any)
const EmpiresSlugRoute = EmpiresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EmpiresRoute,
} as any)
const HeroesIndexRoute = HeroesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeroesRoute,
} as any)
const HeroesSlugRoute = HeroesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HeroesRoute,
} as any)
const ScientistsIndexRoute = ScientistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScientistsRoute,
} as any)
const ScientistsSlugRoute = ScientistsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScientistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abbasid': typeof AbbasidRoute
  '/about': typeof AboutRoute
  '/al-andalus': typeof AlAndalusRoute
  '/assistant': typeof AssistantRoute
  '/battles': typeof BattlesRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRouteWithChildren
  '/empires': typeof EmpiresRouteWithChildren
  '/first-wahi': typeof FirstWahiRoute
  '/golden-age': typeof GoldenAgeRoute
  '/heroes': typeof HeroesRouteWithChildren
  '/hijrah': typeof HijrahRoute
  '/khulafa': typeof KhulafaRoute
  '/library': typeof LibraryRoute
  '/ottoman': typeof OttomanRoute
  '/palestine': typeof PalestineRoute
  '/pre-islam': typeof PreIslamRoute
  '/privacy': typeof PrivacyRoute
  '/prophet': typeof ProphetRoute
  '/quiz': typeof QuizRoute
  '/scholars': typeof ScholarsRoute
  '/scientists': typeof ScientistsRouteWithChildren
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/umayyad': typeof UmayyadRoute
  '/videos': typeof VideosRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/empires/$slug': typeof EmpiresSlugRoute
  '/heroes/$slug': typeof HeroesSlugRoute
  '/scientists/$slug': typeof ScientistsSlugRoute
  '/countries/': typeof CountriesIndexRoute
  '/empires/': typeof EmpiresIndexRoute
  '/heroes/': typeof HeroesIndexRoute
  '/scientists/': typeof ScientistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abbasid': typeof AbbasidRoute
  '/about': typeof AboutRoute
  '/al-andalus': typeof AlAndalusRoute
  '/assistant': typeof AssistantRoute
  '/battles': typeof BattlesRoute
  '/contact': typeof ContactRoute
  '/first-wahi': typeof FirstWahiRoute
  '/golden-age': typeof GoldenAgeRoute
  '/hijrah': typeof HijrahRoute
  '/khulafa': typeof KhulafaRoute
  '/library': typeof LibraryRoute
  '/ottoman': typeof OttomanRoute
  '/palestine': typeof PalestineRoute
  '/pre-islam': typeof PreIslamRoute
  '/privacy': typeof PrivacyRoute
  '/prophet': typeof ProphetRoute
  '/quiz': typeof QuizRoute
  '/scholars': typeof ScholarsRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/umayyad': typeof UmayyadRoute
  '/videos': typeof VideosRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/empires/$slug': typeof EmpiresSlugRoute
  '/heroes/$slug': typeof HeroesSlugRoute
  '/scientists/$slug': typeof ScientistsSlugRoute
  '/countries': typeof CountriesIndexRoute
  '/empires': typeof EmpiresIndexRoute
  '/heroes': typeof HeroesIndexRoute
  '/scientists': typeof ScientistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abbasid': typeof AbbasidRoute
  '/about': typeof AboutRoute
  '/al-andalus': typeof AlAndalusRoute
  '/assistant': typeof AssistantRoute
  '/battles': typeof BattlesRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRouteWithChildren
  '/empires': typeof EmpiresRouteWithChildren
  '/first-wahi': typeof FirstWahiRoute
  '/golden-age': typeof GoldenAgeRoute
  '/heroes': typeof HeroesRouteWithChildren
  '/hijrah': typeof HijrahRoute
  '/khulafa': typeof KhulafaRoute
  '/library': typeof LibraryRoute
  '/ottoman': typeof OttomanRoute
  '/palestine': typeof PalestineRoute
  '/pre-islam': typeof PreIslamRoute
  '/privacy': typeof PrivacyRoute
  '/prophet': typeof ProphetRoute
  '/quiz': typeof QuizRoute
  '/scholars': typeof ScholarsRoute
  '/scientists': typeof ScientistsRouteWithChildren
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/umayyad': typeof UmayyadRoute
  '/videos': typeof VideosRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/empires/$slug': typeof EmpiresSlugRoute
  '/heroes/$slug': typeof HeroesSlugRoute
  '/scientists/$slug': typeof ScientistsSlugRoute
  '/countries/': typeof CountriesIndexRoute
  '/empires/': typeof EmpiresIndexRoute
  '/heroes/': typeof HeroesIndexRoute
  '/scientists/': typeof ScientistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abbasid'
    | '/about'
    | '/al-andalus'
    | '/assistant'
    | '/battles'
    | '/contact'
    | '/countries'
    | '/empires'
    | '/first-wahi'
    | '/golden-age'
    | '/heroes'
    | '/hijrah'
    | '/khulafa'
    | '/library'
    | '/ottoman'
    | '/palestine'
    | '/pre-islam'
    | '/privacy'
    | '/prophet'
    | '/quiz'
    | '/scholars'
    | '/scientists'
    | '/search'
    | '/terms'
    | '/timeline'
    | '/umayyad'
    | '/videos'
    | '/countries/$slug'
    | '/empires/$slug'
    | '/heroes/$slug'
    | '/scientists/$slug'
    | '/countries/'
    | '/empires/'
    | '/heroes/'
    | '/scientists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abbasid'
    | '/about'
    | '/al-andalus'
    | '/assistant'
    | '/battles'
    | '/contact'
    | '/first-wahi'
    | '/golden-age'
    | '/hijrah'
    | '/khulafa'
    | '/library'
    | '/ottoman'
    | '/palestine'
    | '/pre-islam'
    | '/privacy'
    | '/prophet'
    | '/quiz'
    | '/scholars'
    | '/search'
    | '/terms'
    | '/timeline'
    | '/umayyad'
    | '/videos'
    | '/countries/$slug'
    | '/empires/$slug'
    | '/heroes/$slug'
    | '/scientists/$slug'
    | '/countries'
    | '/empires'
    | '/heroes'
    | '/scientists'
  id:
    | '__root__'
    | '/'
    | '/abbasid'
    | '/about'
    | '/al-andalus'
    | '/assistant'
    | '/battles'
    | '/contact'
    | '/countries'
    | '/empires'
    | '/first-wahi'
    | '/golden-age'
    | '/heroes'
    | '/hijrah'
    | '/khulafa'
    | '/library'
    | '/ottoman'
    | '/palestine'
    | '/pre-islam'
    | '/privacy'
    | '/prophet'
    | '/quiz'
    | '/scholars'
    | '/scientists'
    | '/search'
    | '/terms'
    | '/timeline'
    | '/umayyad'
    | '/videos'
    | '/countries/$slug'
    | '/empires/$slug'
    | '/heroes/$slug'
    | '/scientists/$slug'
    | '/countries/'
    | '/empires/'
    | '/heroes/'
    | '/scientists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbbasidRoute: typeof AbbasidRoute
  AboutRoute: typeof AboutRoute
  AlAndalusRoute: typeof AlAndalusRoute
  AssistantRoute: typeof AssistantRoute
  BattlesRoute: typeof BattlesRoute
  ContactRoute: typeof ContactRoute
  CountriesRoute: typeof CountriesRouteWithChildren
  EmpiresRoute: typeof EmpiresRouteWithChildren
  FirstWahiRoute: typeof FirstWahiRoute
  GoldenAgeRoute: typeof GoldenAgeRoute
  HeroesRoute: typeof HeroesRouteWithChildren
  HijrahRoute: typeof HijrahRoute
  KhulafaRoute: typeof KhulafaRoute
  LibraryRoute: typeof LibraryRoute
  OttomanRoute: typeof OttomanRoute
  PalestineRoute: typeof PalestineRoute
  PreIslamRoute: typeof PreIslamRoute
  PrivacyRoute: typeof PrivacyRoute
  ProphetRoute: typeof ProphetRoute
  QuizRoute: typeof QuizRoute
  ScholarsRoute: typeof ScholarsRoute
  ScientistsRoute: typeof ScientistsRouteWithChildren
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
  UmayyadRoute: typeof UmayyadRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abbasid': {
      id: '/abbasid'
      path: '/abbasid'
      fullPath: '/abbasid'
      preLoaderRoute: typeof AbbasidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/al-andalus': {
      id: '/al-andalus'
      path: '/al-andalus'
      fullPath: '/al-andalus'
      preLoaderRoute: typeof AlAndalusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battles': {
      id: '/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof BattlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empires': {
      id: '/empires'
      path: '/empires'
      fullPath: '/empires'
      preLoaderRoute: typeof EmpiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-wahi': {
      id: '/first-wahi'
      path: '/first-wahi'
      fullPath: '/first-wahi'
      preLoaderRoute: typeof FirstWahiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golden-age': {
      id: '/golden-age'
      path: '/golden-age'
      fullPath: '/golden-age'
      preLoaderRoute: typeof GoldenAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hijrah': {
      id: '/hijrah'
      path: '/hijrah'
      fullPath: '/hijrah'
      preLoaderRoute: typeof HijrahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khulafa': {
      id: '/khulafa'
      path: '/khulafa'
      fullPath: '/khulafa'
      preLoaderRoute: typeof KhulafaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ottoman': {
      id: '/ottoman'
      path: '/ottoman'
      fullPath: '/ottoman'
      preLoaderRoute: typeof OttomanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palestine': {
      id: '/palestine'
      path: '/palestine'
      fullPath: '/palestine'
      preLoaderRoute: typeof PalestineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-islam': {
      id: '/pre-islam'
      path: '/pre-islam'
      fullPath: '/pre-islam'
      preLoaderRoute: typeof PreIslamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prophet': {
      id: '/prophet'
      path: '/prophet'
      fullPath: '/prophet'
      preLoaderRoute: typeof ProphetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholars': {
      id: '/scholars'
      path: '/scholars'
      fullPath: '/scholars'
      preLoaderRoute: typeof ScholarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scientists': {
      id: '/scientists'
      path: '/scientists'
      fullPath: '/scientists'
      preLoaderRoute: typeof ScientistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umayyad': {
      id: '/umayyad'
      path: '/umayyad'
      fullPath: '/umayyad'
      preLoaderRoute: typeof UmayyadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof CountriesRoute
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof CountriesRoute
    }
    '/empires/': {
      id: '/empires/'
      path: '/'
      fullPath: '/empires/'
      preLoaderRoute: typeof EmpiresIndexRouteImport
      parentRoute: typeof EmpiresRoute
    }
    '/empires/$slug': {
      id: '/empires/$slug'
      path: '/$slug'
      fullPath: '/empires/$slug'
      preLoaderRoute: typeof EmpiresSlugRouteImport
      parentRoute: typeof EmpiresRoute
    }
    '/heroes/': {
      id: '/heroes/'
      path: '/'
      fullPath: '/heroes/'
      preLoaderRoute: typeof HeroesIndexRouteImport
      parentRoute: typeof HeroesRoute
    }
    '/heroes/$slug': {
      id: '/heroes/$slug'
      path: '/$slug'
      fullPath: '/heroes/$slug'
      preLoaderRoute: typeof HeroesSlugRouteImport
      parentRoute: typeof HeroesRoute
    }
    '/scientists/': {
      id: '/scientists/'
      path: '/'
      fullPath: '/scientists/'
      preLoaderRoute: typeof ScientistsIndexRouteImport
      parentRoute: typeof ScientistsRoute
    }
    '/scientists/$slug': {
      id: '/scientists/$slug'
      path: '/$slug'
      fullPath: '/scientists/$slug'
      preLoaderRoute: typeof ScientistsSlugRouteImport
      parentRoute: typeof ScientistsRoute
    }
  }
}

interface CountriesRouteChildren {
  CountriesSlugRoute: typeof CountriesSlugRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
}

const CountriesRouteChildren: CountriesRouteChildren = {
  CountriesSlugRoute: CountriesSlugRoute,
  CountriesIndexRoute: CountriesIndexRoute,
}

const CountriesRouteWithChildren = CountriesRoute._addFileChildren(
  CountriesRouteChildren,
)

interface EmpiresRouteChildren {
  EmpiresSlugRoute: typeof EmpiresSlugRoute
  EmpiresIndexRoute: typeof EmpiresIndexRoute
}

const EmpiresRouteChildren: EmpiresRouteChildren = {
  EmpiresSlugRoute: EmpiresSlugRoute,
  EmpiresIndexRoute: EmpiresIndexRoute,
}

const EmpiresRouteWithChildren =
  EmpiresRoute._addFileChildren(EmpiresRouteChildren)

interface HeroesRouteChildren {
  HeroesSlugRoute: typeof HeroesSlugRoute
  HeroesIndexRoute: typeof HeroesIndexRoute
}

const HeroesRouteChildren: HeroesRouteChildren = {
  HeroesSlugRoute: HeroesSlugRoute,
  HeroesIndexRoute: HeroesIndexRoute,
}

const HeroesRouteWithChildren =
  HeroesRoute._addFileChildren(HeroesRouteChildren)

interface ScientistsRouteChildren {
  ScientistsSlugRoute: typeof ScientistsSlugRoute
  ScientistsIndexRoute: typeof ScientistsIndexRoute
}

const ScientistsRouteChildren: ScientistsRouteChildren = {
  ScientistsSlugRoute: ScientistsSlugRoute,
  ScientistsIndexRoute: ScientistsIndexRoute,
}

const ScientistsRouteWithChildren = ScientistsRoute._addFileChildren(
  ScientistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbbasidRoute: AbbasidRoute,
  AboutRoute: AboutRoute,
  AlAndalusRoute: AlAndalusRoute,
  AssistantRoute: AssistantRoute,
  BattlesRoute: BattlesRoute,
  ContactRoute: ContactRoute,
  CountriesRoute: CountriesRouteWithChildren,
  EmpiresRoute: EmpiresRouteWithChildren,
  FirstWahiRoute: FirstWahiRoute,
  GoldenAgeRoute: GoldenAgeRoute,
  HeroesRoute: HeroesRouteWithChildren,
  HijrahRoute: HijrahRoute,
  KhulafaRoute: KhulafaRoute,
  LibraryRoute: LibraryRoute,
  OttomanRoute: OttomanRoute,
  PalestineRoute: PalestineRoute,
  PreIslamRoute: PreIslamRoute,
  PrivacyRoute: PrivacyRoute,
  ProphetRoute: ProphetRoute,
  QuizRoute: QuizRoute,
  ScholarsRoute: ScholarsRoute,
  ScientistsRoute: ScientistsRouteWithChildren,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
  UmayyadRoute: UmayyadRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
